In [1]:
import numpy as np

In [2]:
list1=[1,2,3]
np.array(list1)

array([1, 2, 3])

In [4]:
arr=np.array([1,2,3,4,5,4])
arr

array([1, 2, 3, 4, 5, 4])

In [5]:
list_of_list=np.array([[1,2,3,4],[3,6,7,8],[4,4,4,4]])
list_of_list

array([[1, 2, 3, 4],
       [3, 6, 7, 8],
       [4, 4, 4, 4]])

In [6]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [7]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(1,31,5)

array([ 1,  6, 11, 16, 21, 26])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [24]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(3,5)

array([[0.40920219, 0.91470995, 0.58136323, 0.04427528, 0.15560103],
       [0.93531657, 0.3292893 , 0.59774349, 0.67679837, 0.56308697],
       [0.20164499, 0.24396558, 0.42707528, 0.13162385, 0.36093929]])

In [27]:
arr = np.random.rand(3,4)
arr

array([[0.16943219, 0.95551872, 0.53936159, 0.68648175],
       [0.39018884, 0.58753248, 0.7656315 , 0.05933233],
       [0.84445538, 0.60652084, 0.70935402, 0.74818717]])

In [29]:
np.random.randint(4,10)

7

In [30]:
np.random.randn(4,5)

array([[-0.78244599, -1.47987566, -0.98798437, -1.69003818,  0.10949009],
       [-0.6129779 ,  0.80171295, -2.26485237, -0.4689838 , -1.0906815 ],
       [ 0.59954939,  0.51527957, -0.08839625,  1.09905417,  1.58749781],
       [-1.35100311,  0.12942108, -0.2291688 ,  0.72695374,  0.52356128]])

In [31]:
np.random.randint(20,40,100)

array([22, 29, 32, 20, 28, 23, 25, 24, 37, 32, 31, 39, 20, 39, 30, 21, 27,
       30, 32, 20, 35, 30, 24, 38, 28, 35, 39, 32, 32, 38, 20, 27, 24, 26,
       30, 30, 24, 27, 27, 23, 35, 34, 24, 24, 21, 21, 25, 37, 29, 39, 26,
       37, 39, 25, 25, 22, 34, 21, 28, 34, 27, 22, 30, 26, 33, 27, 32, 22,
       22, 26, 22, 38, 27, 30, 21, 29, 21, 36, 37, 34, 25, 28, 35, 37, 34,
       22, 26, 32, 30, 30, 26, 38, 24, 22, 24, 36, 26, 21, 22, 25])

In [32]:
simp_arr=np.arange(30)
simp_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
simp_arr.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [36]:
simp_arr.max()

29

In [37]:
simp_arr.min()

0

In [39]:
simp_arr.argmax()

29

In [43]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
samp_arr=np.arange(10,21)
samp_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
a=np.random.rand(4,5)
a

array([[0.6157211 , 0.64790306, 0.17854069, 0.92028921, 0.90404904],
       [0.42151925, 0.86616812, 0.72587798, 0.69998349, 0.48189409],
       [0.88176392, 0.78741065, 0.56503941, 0.67722606, 0.01469762],
       [0.87454186, 0.30076009, 0.91670518, 0.03420523, 0.2492302 ]])

In [50]:
a.T

array([[0.6157211 , 0.42151925, 0.88176392, 0.87454186],
       [0.64790306, 0.86616812, 0.78741065, 0.30076009],
       [0.17854069, 0.72587798, 0.56503941, 0.91670518],
       [0.92028921, 0.69998349, 0.67722606, 0.03420523],
       [0.90404904, 0.48189409, 0.01469762, 0.2492302 ]])

In [52]:
samp_arr=np.arange(10,21)
samp_arr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [53]:
samp_arr[0]

10

In [54]:
samp_arr[2:5]

array([12, 13, 14])

In [56]:
samp_arr[1:4]=100
samp_arr

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [64]:
sa_arr=np.arange(10,21)
sa_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [65]:
sa_arr[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [66]:
sub_sa_arr = sa_arr[0:7]
sub_sa_arr

array([10, 11, 12, 13, 14, 15, 16])

In [67]:
sub_sa_arr[:]=100

In [68]:
sub_sa_arr

array([100, 100, 100, 100, 100, 100, 100])

# TWO DIMENSIONAL ARRAY

In [69]:
import numpy as np 

In [70]:
samp_arr = np.array([[1,2,3,4],[3,4,22,2],[5,535,53,53]])
samp_arr

array([[  1,   2,   3,   4],
       [  3,   4,  22,   2],
       [  5, 535,  53,  53]])

In [71]:
samp_arr[2,3]

53

In [72]:
samp_arr[2,:]

array([  5, 535,  53,  53])

In [73]:
samp_arr[2]

array([  5, 535,  53,  53])

In [74]:
samp_arr[:,2]

array([ 3, 22, 53])

In [75]:
samp_arr[:,(3,2)]

array([[ 4,  3],
       [ 2, 22],
       [53, 53]])