In [2]:
import numpy as np

In [3]:
samp_arr = np.arange(1,20)
samp_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
np.exp(samp_arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [5]:
np.sqrt(samp_arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [6]:
np.square(samp_arr)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [7]:
np.log(samp_arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [8]:
np.max(samp_arr)

19

In [9]:
np.min(samp_arr)

1

In [11]:
np.argmax(samp_arr)

18

In [12]:
np.argmin(samp_arr)

0

In [13]:
np.std(samp_arr)

5.477225575051661

In [14]:
np.var(samp_arr)

30.0

In [16]:
np.mean(samp_arr)

10.0

In [17]:
arr = np.random.rand(3,4)
arr

array([[0.02391834, 0.52264617, 0.86987881, 0.29936089],
       [0.161752  , 0.23389358, 0.63446394, 0.31362891],
       [0.60351429, 0.98979567, 0.14677133, 0.4885494 ]])

In [20]:
np.round(arr,decimals=2)

array([[0.02, 0.52, 0.87, 0.3 ],
       [0.16, 0.23, 0.63, 0.31],
       [0.6 , 0.99, 0.15, 0.49]])

In [21]:
sports=np.array(['cricket','foootball','hockey','cricket'])
sports

array(['cricket', 'foootball', 'hockey', 'cricket'], dtype='<U9')

In [22]:
np.unique(sports)

array(['cricket', 'foootball', 'hockey'], dtype='<U9')

### PANDAS

In [23]:
import pandas as pd

In [26]:

sports1 = pd.Series([1,2,3,4],index=['cricket','fotball','baseball','golf'])
sports

array(['cricket', 'foootball', 'hockey', 'cricket'], dtype='<U9')

In [31]:
sports1['fotball']

2

In [34]:
sports2 =  pd.Series([11,2,3,4],index=['cricket','fotball','basketball','golf'])
sports

array(['cricket', 'foootball', 'hockey', 'cricket'], dtype='<U9')

In [35]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
fotball        4.0
golf           8.0
dtype: float64

In [43]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.215175  0.952162  0.075281  0.515120  0.163797
B  0.015420  0.045286  0.220839  0.129333  0.213460
C  0.578896  0.414180  0.218166  0.594082  0.727303
D  0.009558  0.821744  0.644584  0.991958  0.328948
E  0.064684  0.211510  0.077985  0.906003  0.170454
F  0.015107  0.474165  0.196906  0.204053  0.813733
G  0.819847  0.746668  0.309076  0.741616  0.182757
H  0.622535  0.423384  0.628242  0.550664  0.320126

In [44]:
df1['score1']

A    0.215175
B    0.015420
C    0.578896
D    0.009558
E    0.064684
F    0.015107
G    0.819847
H    0.622535
Name: score1, dtype: float64

In [46]:
df1[['score1','score2']]

score1    score2
A  0.215175  0.952162
B  0.015420  0.045286
C  0.578896  0.414180
D  0.009558  0.821744
E  0.064684  0.211510
F  0.015107  0.474165
G  0.819847  0.746668
H  0.622535  0.423384

In [48]:
df1['score6']=df1['score1']+df1['score2']
df1['score6']

A    1.167337
B    0.060706
C    0.993076
D    0.831301
E    0.276193
F    0.489271
G    1.566515
H    1.045920
Name: score6, dtype: float64

In [53]:
df2={'ID': ['101','102','103','104','105'],'NAME':['samarth','ayush','deepika','prakhar','saad'],'PROFIT':[12,20,34,35,44]}
df=pd.DataFrame(df2)
df

ID     NAME  PROFIT
0  101  samarth      12
1  102    ayush      20
2  103  deepika      34
3  104  prakhar      35
4  105     saad      44

In [54]:
df['ID']

0    101
1    102
2    103
3    104
4    105
Name: ID, dtype: object

In [55]:
df[['ID','NAME']]

ID     NAME
0  101  samarth
1  102    ayush
2  103  deepika
3  104  prakhar
4  105     saad

In [56]:
 df.drop('ID',axis=1)

NAME  PROFIT
0  samarth      12
1    ayush      20
2  deepika      34
3  prakhar      35
4     saad      44